### ISSUE TITLE
Request for Detailed README for Easier Setup and Usage.

### ISSUE THREAD

**Issue by jiangpinghuang** [dropreg/OpenLTG-MLM#1]
Hi authors,
Firstly, I want to express my gratitude for the work you've shared through this repository. It's an exciting project, and I'm keen to try it out.
However, I've found that the README lacks some details that would make it easier for newcomers to understand how to get started. Specifically, it would be great to have:
1. A more detailed installation guide, including any dependencies required.
2. Usage examples for common scenarios.
3. Troubleshooting tips or common pitfalls to avoid.
Understanding that you're likely busy, I appreciate any time you can spare to improve the documentation. If I manage to figure out some of the steps on my own, I'd be more than happy to contribute by updating the README and submitting a pull request.
Thank you for your time and consideration.

**Comment by dropreg** [comment]
I apologize for not updating the code repository with detailed instructions. 
We have now updated it with comprehensive installation and usage guides for quick start.
